version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=linebot_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - 5432
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./linebot:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=linebot_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=secret_key
    env_file:
    - .env
    depends_on:
      - db