# Generated by Django 3.2.5 on 2022-06-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getIdToken', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('developerId', models.CharField(max_length=100)),
                ('flowChart', models.CharField(max_length=100)),
                ('createdAt', models.CharField(max_length=100)),
                ('updateAt', models.CharField(max_length=100)),
            ],
        ),
    ]
