# Generated by Django 3.2.5 on 2022-09-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getIdToken', '0003_alter_bot_flowchart'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
