# Generated by Django 3.2.5 on 2022-09-13 12:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('getIdToken', '0004_bot_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='bot',
            old_name='flowChart',
            new_name='flowchart',
        ),
        migrations.RenameField(
            model_name='bot',
            old_name='updateAt',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='activation',
            old_name='bot_id',
            new_name='bot'
        ),
        migrations.RenameField(
            model_name='activation',
            old_name='user_id',
            new_name='user'
        ),
        migrations.RenameField(
            model_name='bot',
            old_name='developerId',
            new_name='created_by'
        ),
        migrations.AlterField(
            model_name='activation',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getIdToken.bot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getIdToken.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bot',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getIdToken.user'),
            preserve_default=False,
        ),
    ]
