# Generated by Django 3.2.5 on 2022-09-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getIdToken', '0005_auto_20220913_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.TextField(max_length=100),
        ),
    ]
