# Generated by Django 3.2.5 on 2022-09-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getIdToken', '0008_auto_20220913_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='created_by',
        ),
    ]
