# Generated by Django 3.2.5 on 2022-09-13 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("getIdToken", "0009_remove_bot_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="getIdToken.user"
            ),
        ),
    ]
