# Generated by Django 3.2.5 on 2022-09-15 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("getIdToken", "0010_bot_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="getIdToken.user"
            ),
        ),
        migrations.AlterField(
            model_name="activation",
            name="bot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="getIdToken.bot"
            ),
        ),
    ]
