# Generated by Django 3.2.5 on 2022-09-15 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getIdToken', '0011_auto_20220915_0840'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='activation',
            name='bot',
        ),
        migrations.RemoveField(
            model_name='activation',
            name='user',
        ),
    ]
