# Generated by Django 3.2.5 on 2022-09-15 08:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("getIdToken", "0012_auto_20220915_0847"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="bot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="getIdToken.bot"
            ),
        ),
        migrations.AddField(
            model_name="activation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="getIdToken.user"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="activation",
            unique_together={("user", "bot")},
        ),
    ]
