# Generated by Django 3.2.5 on 2022-09-16 12:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("getIdToken", "0013_auto_20220915_0847"),
    ]

    operations = [
        migrations.AddField(
            model_name="activation",
            name="snapshot",
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name="activation",
            name="id",
        ),
        migrations.AlterField(
            model_name="bot",
            name="flowchart",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="activation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="getIdToken.user",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name="activation",
            unique_together=set(),
        ),
    ]
