# Generated by Django 3.2.5 on 2022-09-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getIdToken', '0014_auto_20220916_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='snapshot',
            field=models.TextField(default=''),
        ),
    ]
